import { Container, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';

// mantine styles
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <Notifications />
          <Container>{children}</Container>
        </MantineProvider>
      </body>
    </html>
  );
}
