import { ColorSchemeScript, Container, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';

// mantine styles
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import { SessionProvider } from 'next-auth/react';
import Header from '@/components/header/Header';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ColorSchemeScript defaultColorScheme="light" />
        {/* <SessionProvider> */}
        <MantineProvider defaultColorScheme="light">
          <Notifications />
          <Container>{children}</Container>
        </MantineProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
