import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';

// mantine styles
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
        <ColorSchemeScript defaultColorScheme="light" />
        {/* <SessionProvider> */}
        <MantineProvider defaultColorScheme="light">
          <Notifications />
          {children}
        </MantineProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
